//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab1
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_sage_book
    {
        public int sageBookId { get; set; }
        public Nullable<int> sageId { get; set; }
        public Nullable<int> bookId { get; set; }
    
        public virtual table_book table_book { get; set; }
        public virtual table_sage table_sage { get; set; }
    }
}
